name: Gifts
main: gifts.tjnome.main.Gifts
version: 1.0.5
website: 'http://www.minecraft.no'
authors: ['tjnome']
description: Gifts Plugin
commands:
    gift:
        aliases:
        - gave
        description: Set out a chest with goodies inside.
        usage: |
               /<command>